wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1647985999
    t:
      1:
        - 1
      2:
        - 1
      3:
        - 13
        - 14
        - 16
      4: 3.9.10
      5: 0.12.10
      8:
        - 5
auto_resume:
  desc: null
  value: true
datasets:
  desc: null
  value:
    train:
      batch_size_per_gpu: 8
      betag_range:
        - 0.5
        - 4
      betag_range2:
        - 0.5
        - 4
      betap_range:
        - 1
        - 2
      betap_range2:
        - 1
        - 2
      blur_kernel_size: 15
      blur_kernel_size2: 15
      blur_sigma:
        - 0.2
        - 3
      blur_sigma2:
        - 0.2
        - 1.5
      dataroot_gt: datasets/super_res_dataset
      dataset_enlarge_ratio: 1
      final_sinc_prob: 0.1
      gt_size: 256
      io_backend:
        type: disk
      kernel_list:
        - iso
        - aniso
        - generalized_iso
        - generalized_aniso
        - plateau_iso
        - plateau_aniso
      kernel_list2:
        - iso
        - aniso
        - generalized_iso
        - generalized_aniso
        - plateau_iso
        - plateau_aniso
      kernel_prob:
        - 0.45
        - 0.25
        - 0.12
        - 0.03
        - 0.12
        - 0.03
      kernel_prob2:
        - 0.45
        - 0.25
        - 0.12
        - 0.03
        - 0.12
        - 0.03
      meta_info: datasets/super_res_HD/meta_info/train_info_BLM_BRU_OLD_UNI.txt
      name: Combined_BLM+OLD+BRU+UNI
      num_worker_per_gpu: 4
      phase: train
      prefetch_mode: null
      scale: 2
      sinc_prob: 0.1
      sinc_prob2: 0.1
      type: RealESRGANDataset
      use_hflip: true
      use_rot: false
      use_shuffle: true
dist:
  desc: null
  value: true
dist_params:
  desc: null
  value:
    backend: nccl
    port: 29500
gan_gt_usm:
  desc: null
  value: false
gaussian_noise_prob:
  desc: null
  value: 0.1
gaussian_noise_prob2:
  desc: null
  value: 0.2
gray_noise_prob:
  desc: null
  value: 0.1
gray_noise_prob2:
  desc: null
  value: 0.1
gt_size:
  desc: null
  value: 256
is_train:
  desc: null
  value: true
jpeg_range:
  desc: null
  value:
    - 30
    - 95
jpeg_range2:
  desc: null
  value:
    - 90
    - 100
l1_gt_usm:
  desc: null
  value: true
logger:
  desc: null
  value:
    print_freq: 100
    save_checkpoint_freq: 2500.0
    use_tb_logger: true
    wandb:
      project: super-res
      resume_id: null
manual_seed:
  desc: null
  value: 0
model_type:
  desc: null
  value: RealESRGANModel
name:
  desc: null
  value: finetune_BLM+OLD+BRU+UNIx2_vanilla
network_d:
  desc: null
  value:
    num_feat: 64
    num_in_ch: 3
    skip_connection: true
    type: UNetDiscriminatorSN
network_g:
  desc: null
  value:
    num_block: 23
    num_feat: 64
    num_grow_ch: 32
    num_in_ch: 3
    num_out_ch: 3
    scale: 2
    type: RRDBNet
noise_range:
  desc: null
  value:
    - 1
    - 3
noise_range2:
  desc: null
  value:
    - 1
    - 5
num_gpu:
  desc: null
  value: 2
path:
  desc: null
  value:
    experiments_root: /home/adithya/adithya/Real-ESRGAN/experiments/finetune_BLM+OLD+BRUx2_vanilla
    log: /home/adithya/adithya/Real-ESRGAN/experiments/finetune_BLM+OLD+BRUx2_vanilla
    models: /home/adithya/adithya/Real-ESRGAN/experiments/finetune_BLM+OLD+BRUx2_vanilla/models
    param_key_d: params
    param_key_g: params_ema
    pretrain_network_d: experiments/pretrained_models/RealESRGAN_x2plus_netD.pth
    pretrain_network_g: experiments/pretrained_models/RealESRGAN_x2plus.pth
    resume_state: null
    strict_load_d: true
    strict_load_g: true
    training_states: /home/adithya/adithya/Real-ESRGAN/experiments/finetune_BLM+OLD+BRUx2_vanilla/training_states
    visualization: /home/adithya/adithya/Real-ESRGAN/experiments/finetune_BLM+OLD+BRUx2_vanilla/visualization
percep_gt_usm:
  desc: null
  value: true
poisson_scale_range:
  desc: null
  value:
    - 0.05
    - 1
poisson_scale_range2:
  desc: null
  value:
    - 0.05
    - 0.5
queue_size:
  desc: null
  value: 160
rank:
  desc: null
  value: 0
resize_prob:
  desc: null
  value:
    - 0.2
    - 0.2
    - 0.9
resize_prob2:
  desc: null
  value:
    - 0.1
    - 0.1
    - 0.9
resize_range:
  desc: null
  value:
    - 0.15
    - 1.5
resize_range2:
  desc: null
  value:
    - 0.3
    - 1.2
root_path:
  desc: null
  value: /home/adithya/adithya/Real-ESRGAN
scale:
  desc: null
  value: 2
second_blur_prob:
  desc: null
  value: 0.1
train:
  desc: null
  value:
    ema_decay: 0.999
    gan_opt:
      fake_label_val: 0.0
      gan_type: vanilla
      loss_weight: 0.1
      real_label_val: 1.0
      type: GANLoss
    net_d_init_iters: 0
    net_d_iters: 1
    optim_d:
      betas:
        - 0.9
        - 0.99
      lr: 0.0001
      type: Adam
      weight_decay: 0
    optim_g:
      betas:
        - 0.9
        - 0.99
      lr: 0.0001
      type: Adam
      weight_decay: 0
    perceptual_opt:
      criterion: l1
      layer_weights:
        conv1_2: 0.1
        conv2_2: 0.1
        conv3_4: 1
        conv4_4: 1
        conv5_4: 1
      perceptual_weight: 1.0
      range_norm: false
      style_weight: 0
      type: PerceptualLoss
      use_input_norm: true
      vgg_type: vgg19
    pixel_opt:
      loss_weight: 1.0
      reduction: mean
      type: L1Loss
    scheduler:
      gamma: 0.5
      milestones:
        - 400000
      type: MultiStepLR
    total_iter: 400000
    warmup_iter: -1
world_size:
  desc: null
  value: 2
